name = "ai-perspective-worker"
main = "workers/AI_Perspective_worker.js"
compatibility_date = "2024-01-01"

# 如果需要绑定自定义域名
# [routes]
# pattern = "api.yourdomain.com/*"
# zone_id = "your-zone-id"

[vars]
# 这些变量会在部署时被设置
# GEMINI_API_KEY = "your-api-key" 